---
name: softhsm

instance_groups:
- name: softhsm
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: softhsm
    release: softhsm
    properties:
      slots:
      - slot:     0
        label:    bosh
        so_pin:   ((hsm-4digit-so-pin)) # security officer pin
        user_pin: ((hsm-4digit-user-pin)) # user pin

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: softhsm
  version: latest # TODO: update after first final release
  # url:            TODO: update after first final release
  # sha1:           TODO: update after first final release
